version: "3"
services:
    web:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django_book_website
        ports:
            - "8010:8010"
        volumes:
            - .:/app
        command: >
            sh -c "python manage.py migrate
                  python manage.py runserver 0.0.0.0:8010"
        environment:
            DB_HOST: db
            DB_NAME: app
            DB_USER: postgres
            DB_PASSWORD: 12345
        depends_on:
            - db
    db:
        image: postgres:10-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
        ports:
            - "5432:5432"
        volumes:
            - /datadir:/var/lib/postgresql/data
volumes:
    datadir:



