# Generated by Django 3.1.5 on 2021-01-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='aurthor',
            new_name='author',
        ),
    ]
