# Generated by Django 3.1.5 on 2021-01-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_auto_20210115_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='email',
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=5),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
