# Generated by Django 3.1.8 on 2021-04-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_auto_20210121_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=2),
        ),
    ]
